Repository fingerprintjs/fingerprint.com, pull requests merged in 2023-03, with the labels that each got.

#1121 Update Integrations and SDKs pages “sdks”
  content/integrations-sdks/sdks.md
  static/img/uploads/integrationsCards/javasdkim.png
Labels: netlify-cms/draft

#1098 Update Blog “when-love-is-too-blind-how-romance-scams-can-lead-to-credit-card-fraud-on-your-site”
  content/blog/when-love-is-too-blind-how-romance-scams-can-lead-to-credit-card-fraud-on-your-site.md
Labels: netlify-cms/pending_review

#1123 Create Blog “fingerprint-partners-with-spec-to-provide-real-time-user-insights-that-reduce-fraud-and-deliver-frictionless-digital-experiences”
  content/blog/fingerprint-partners-with-spec-to-provide-real-time-user-insights-that-reduce-fraud-and-deliver-frictionless-digital-experiences.md
  static/img/uploads/fpspec-orange.png
  static/img/uploads/fpspec-white.png
Labels: netlify-cms/draft

#1125 Update Press page “press-page”
  content/press/press-page.md
Labels: netlify-cms/pending_publish

#1131 Update Author “kevin-roy”
  content/author/kevin-roy.md
  static/img/uploads/headshotcroppedkevin.jpeg
Labels: netlify-cms/pending_publish

#1132 Update Press page “press-page”
  content/press/press-page.md
Labels: netlify-cms/pending_publish

#1135 Update Blog “the-7-cryptocurrency-scams-you-need-to-know-about-in-2023”
  content/blog/the-7-cryptocurrency-scams-you-need-to-know-about-in-2023.md
Labels: netlify-cms/draft

#1140 Update Blog “fingerprint-triples-revenue-and-users-crosses-one-billion-monthly-api-calls”
  content/blog/fingerprint-triples-revenue-and-users-crosses-one-billion-monthly-api-calls.md
Labels: netlify-cms/pending_publish

#1139 Update Notification Bar “notificationBar”
  content/notification-bar/notificationConfig.yml
Labels: netlify-cms/pending_publish

#1141 Update Blog “fingerprint-triples-revenue-and-users-crosses-one-billion-monthly-api-calls”
  content/blog/fingerprint-triples-revenue-and-users-crosses-one-billion-monthly-api-calls.md
Labels: netlify-cms/pending_publish

#1142 Create Blog “fingerprint-crosses-1-billion-api-calls-and-triples-revenue-and-users-all-in-just-one-year”
  content/blog/fingerprint-crosses-1-billion-api-calls-and-triples-revenue-and-users-all-in-just-one-year.md
  static/img/uploads/20230207_wise_20076.jpg
  static/img/uploads/infographic-social-company.png
  static/img/uploads/infographic-social-devs.png
Labels: netlify-cms/pending_publish

#1145 Create Author “vesta”
  content/author/vesta.md
  static/img/uploads/1657119323707.jpeg
Labels: netlify-cms/pending_review

#1146 Create Blog “online-travel-fraud-–-types-detection-and-prevention”
  content/blog/online-travel-fraud-–-types-detection-and-prevention.md
  static/img/uploads/identity-theft-fraud-report-graph.png
  static/img/uploads/vesta_-guest-post-online-travel-fraud.jpg
Labels: netlify-cms/pending_review

#1147 Create Blog “online-insurance-fraud-types-techniques-prevention”
  content/blog/online-insurance-fraud-types-techniques-prevention.md
  static/img/uploads/insurance-fraud.gif
Labels: netlify-cms/pending_review

#1154 Update Author “dan-pinto”
  content/author/dan-pinto.md
  static/img/uploads/20230207_wise_20196.jpg
Labels: netlify-cms/draft

#1155 Update Author “savannah-copland”
  content/author/savannah-copland.md
  static/img/uploads/20230207_wise_20318.jpg
Labels: netlify-cms/draft

#1156 Update Author “alexey-verkhovsky”
  content/author/alexey-verkhovsky.md
Labels: netlify-cms/draft

#1157 Update Author “martin-makarsky”
  content/author/martin-makarsky.md
Labels: netlify-cms/draft

#1158 Update Author “petr-palata”
  content/author/petr-palata.md
Labels: netlify-cms/draft

#1159 Update Author “ravi-bhanot”
  content/author/ravi-bhanot.md
  static/img/uploads/20230207_wise_20111-1-.jpg
Labels: netlify-cms/pending_review

#1168 Create Blog “how-to-prevent-advertising-fraud”
  content/blog/how-to-prevent-advertising-fraud.md
  static/img/uploads/advertisement-fraud.jpg
Labels: netlify-cms/pending_review

#1178 Update Blog “friendly-fraud-what-it-is-how-to-protect-your-business”
  content/blog/friendly-fraud-what-it-is-how-to-protect-your-business.md
Labels: netlify-cms/pending_review

#1165 Create Author “juraj-uhlar”
  content/author/juraj-uhlar.md
  static/img/uploads/profile_picture.jpeg
Labels: netlify-cms/draft

#1180 Create Blog “what-is-letterboxing-and-can-it-prevent-browser-fingerprinting”
  content/blog/what-is-letterboxing-and-can-it-prevent-browser-fingerprinting.md
  static/img/uploads/anti-fingerprinting-technique_-letterboxing.jpg
Labels: netlify-cms/pending_review

#1164 Update Author “martin-makarsky”
  content/author/martin-makarsky.md
  static/img/uploads/2d96e743e5674f0aa4d51bc39e4ee57042424000015143e1f4849.jpg
Labels: netlify-cms/draft

#1184 Update Blog “account-takeover-indicators-that-businesses-should-know-to-prevent-digital-identity-fraud”
  content/blog/account-takeover-indicators-that-businesses-should-know-to-prevent-digital-identity-fraud.md
Labels: netlify-cms/draft

#1188 Update Blog “webinar-why-accuracy-is-everything-in-device-identification”
  content/blog/webinar-why-accuracy-is-everything-in-device-identification.md
  static/img/uploads/v2.png
Labels: netlify-cms/pending_publish

#1187 Update Blog “webinar-product-launch-detect-bots-in-real-time-with-botd”
  content/blog/webinar-product-launch-detect-bots-in-real-time-with-botd.md
  static/img/uploads/v1.png
Labels: netlify-cms/pending_publish

#1189 Update Blog “webinar-the-state-of-payment-fraud-how-to-prevent-it”
  content/blog/webinar-the-state-of-payment-fraud-how-to-prevent-it.md
  static/img/uploads/blog0.png
Labels: netlify-cms/pending_publish

#1190 Create Blog “what-the-online-gaming-and-gambling-industry-needs-to-know-about-betting-bots”
  content/blog/what-the-online-gaming-and-gambling-industry-needs-to-know-about-betting-bots.md
  static/img/uploads/betting-bots.jpg
Labels: netlify-cms/pending_review

#1191 Update Blog “what-is-letterboxing-and-can-it-prevent-browser-fingerprinting”
  content/blog/what-is-letterboxing-and-can-it-prevent-browser-fingerprinting.md
Labels: netlify-cms/draft

#1201 Update Blog “three’s-a-crowd-how-to-prevent-triangulation-fraud-in-your-business”
  content/blog/three’s-a-crowd-how-to-prevent-triangulation-fraud-in-your-business.md
Labels: netlify-cms/draft

#1200 Update Blog “what-the-online-gaming-and-gambling-industry-needs-to-know-about-betting-bots”
  content/blog/what-the-online-gaming-and-gambling-industry-needs-to-know-about-betting-bots.md
Labels: netlify-cms/pending_review

#1205 Create Blog “omnichannel-fraud-detection-and-prevention-best-practices-to-protect-your-business”
  content/blog/omnichannel-fraud-detection-and-prevention-best-practices-to-protect-your-business.md
  static/img/uploads/omnichannel-fraud.jpg
Labels: netlify-cms/pending_review

#1203 Update Blog “what-is-letterboxing-and-can-it-prevent-browser-fingerprinting”
  content/blog/what-is-letterboxing-and-can-it-prevent-browser-fingerprinting.md
Labels: netlify-cms/pending_review

#1209 Update Blog “6-types-of-ecommerce-fraud-and-how-to-prevent-them-from-compromising-your-online-store”
  content/blog/6-types-of-ecommerce-fraud-and-how-to-prevent-them-from-compromising-your-online-store.md
Labels: netlify-cms/pending_review

#1210 Update Blog “online-marketplace-fraud-how-to-protect-your-business-and-users”
  content/blog/online-marketplace-fraud-how-to-protect-your-business-and-users.md
Labels: netlify-cms/pending_review

#1212 Update Blog “how-to-avoid-online-auction-fraud”
  content/blog/how-to-avoid-online-auction-fraud.md
Labels: netlify-cms/pending_review

#1211 Update Blog “how-online-businesses-can-prevent-gift-card-fraud”
  content/blog/how-online-businesses-can-prevent-gift-card-fraud.md
Labels: netlify-cms/pending_review
