Repository fingerprintjs/fingerprint.com, pull requests merged in 2023-01, with the labels that each got.

#904 Create Blog “2022-fraud-in-the-news”
  content/blog/2022-fraud-in-the-news.md
  static/img/uploads/2022-fraud-in-the-news-wip.jpg
Labels: netlify-cms/pending_publish

#908 Update Blog “fingerprintjs-and-fingerprint-pro-99-5-device-identification-accuracy-explained”
  content/blog/fingerprintjs-and-fingerprint-pro-99-5-device-identification-accuracy-explained.md
Labels: netlify-cms/pending_review

#909 Update Blog “our-company-name-is-now-fingerprint”
  content/blog/our-company-name-is-now-fingerprint.md
Labels: netlify-cms/pending_review

#910 Update Blog “2022-fraud-in-the-news”
  content/blog/2022-fraud-in-the-news.md
  static/admin/config.yml
  vercel.json
Labels: netlify-cms/draft

#918 Create Blog “why-does-identifying-anonymous-and-unique-website-visitors-matter”
  content/blog/why-does-identifying-anonymous-and-unique-website-visitors-matter.md
  static/img/uploads/what-do-unique-visitors-anonymous-visitors-~actually~-mean-when-it-comes-to-identifying-them_.jpg
Labels: netlify-cms/pending_publish

#921 Create Blog “p2p-peer-to-peer-fraud-research-guide”
  content/blog/p2p-peer-to-peer-fraud-research-guide.md
  static/img/uploads/p2p-peer-to-peer-fraud-research-guide.jpg
Labels: netlify-cms/pending_review

#924 Update Blog “credential-stuffing-prevention-a-complete-checklist-for-2021”
  content/blog/credential-stuffing-prevention-a-complete-checklist-for-2021.md
Labels: netlify-cms/pending_review

#1025 Update Blog “storing-anonymous-browsing-preferences-using-browser-fingerprinting”
  content/blog/storing-anonymous-browsing-preferences-using-browser-fingerprinting.md
Labels: netlify-cms/pending_review

#1024 Update Blog “32m-series-b-funding”
  content/blog/32m-series-b-funding.md
Labels: netlify-cms/pending_review

#1007 Update Blog “browser-fingerprinting-for-product-and-growth-teams”
  content/blog/browser-fingerprinting-for-product-and-growth-teams.md
Labels: netlify-cms/draft

#1026 Update Blog “the-retailer’s-holiday-season-fraud-prevention-checklist”
  content/blog/the-retailer’s-holiday-season-fraud-prevention-checklist.md
Labels: netlify-cms/pending_review

#1029 Create Blog “how-to-improve-your-online-user-identification-process”
  content/blog/how-to-improve-your-online-user-identification-process.md
  static/img/uploads/tbd_-why-identification-matters.jpg
Labels: netlify-cms/pending_review

#1028 Update Blog “a-guide-to-ecommerce-merchant-fraud-protection-in-2021”
  content/blog/a-guide-to-ecommerce-merchant-fraud-protection-in-2021.md
Labels: netlify-cms/pending_review

#1031 Update Blog “how-to-improve-your-online-user-identification-process”
  content/blog/how-to-improve-your-online-user-identification-process.md
Labels: netlify-cms/draft

#1035 Create Blog “why-bot-mitigation-is-important”
  content/blog/why-bot-mitigation-is-important.md
  static/img/uploads/why-bot-mitigation-is-important.jpg
Labels: netlify-cms/pending_review

#1036 Update Blog “incognito-mode-detection-detecting-visitors-who-browse-in-incognito-mode”
  content/blog/incognito-mode-detection-detecting-visitors-who-browse-in-incognito-mode.md
Labels: netlify-cms/pending_review

#1037 Update Blog “why-bot-mitigation-is-important”
  content/blog/why-bot-mitigation-is-important.md
Labels: netlify-cms/pending_review

#1039 Update Integrations and SDKs pages “sdks”
  content/integrations-sdks/sdks.md
  static/img/uploads/integrationsCards/netsdk.png
Labels: netlify-cms/draft

#1044 Create Blog “the-7-cryptocurrency-scams-you-need-to-know-about-in-2023”
  content/blog/the-7-cryptocurrency-scams-you-need-to-know-about-in-2023.md
  static/img/uploads/cryptocurrency-fraud.jpg
Labels: netlify-cms/pending_publish

#1049 Update Blog “when-love-is-too-blind-how-romance-scams-can-lead-to-credit-card-fraud-on-your-site”
  content/blog/when-love-is-too-blind-how-romance-scams-can-lead-to-credit-card-fraud-on-your-site.md
Labels: netlify-cms/pending_publish

#1048 Update Notification Bar “notificationBar”
  content/notification-bar/notificationConfig.yml
Labels: netlify-cms/pending_publish
