Repository fingerprintjs/fingerprint.com, pull requests merged in 2023-02, with the labels that each got.

#1053 Create Blog “how-to-improve-your-attribution-strategy-with-device-identification”
  content/blog/how-to-improve-your-attribution-strategy-with-device-identification.md
  static/img/uploads/attribution-product-post.jpg
Labels: netlify-cms/pending_review

#1055 Update Blog “how-to-prevent-chargeback-credit-card-fraud-revenue-loss”
  content/blog/how-to-prevent-chargeback-credit-card-fraud-revenue-loss.md
Labels: netlify-cms/pending_review

#1058 Create Blog “meet-the-fingerprint-team-at-developerweek-2023”
  content/blog/meet-the-fingerprint-team-at-developerweek-2023.md
  static/img/uploads/blog-developerweek.jpg
Labels: netlify-cms/pending_review

#1062 Create Blog “why-are-vpns-ineffective-against-browser-fingerprinting”
  content/blog/why-are-vpns-ineffective-against-browser-fingerprinting.md
  static/img/uploads/why-vpns-are-ineffective-against-browser-fingerprinting.jpg
Labels: netlify-cms/pending_review

#1063 Update Blog “buy-now-pay-later-the-ultimate-research-guide”
  content/blog/buy-now-pay-later-the-ultimate-research-guide.md
Labels: netlify-cms/pending_review

#1064 Update Blog “how-to-improve-your-attribution-strategy-with-device-identification”
  content/blog/how-to-improve-your-attribution-strategy-with-device-identification.md
Labels: netlify-cms/pending_publish

#1065 Update Blog “how-major-payment-processors-handle-chargebacks”
  content/blog/how-major-payment-processors-handle-chargebacks.md
Labels: netlify-cms/pending_review

#1066 Update Blog “how-to-improve-your-attribution-strategy-with-device-identification”
  content/blog/how-to-improve-your-attribution-strategy-with-device-identification.md
Labels: netlify-cms/pending_publish

#1067 Update Blog “default-title-1”
  content/blog/default-title-1.md
Labels: netlify-cms/pending_review

#1069 Create Blog “the-benefits-and-risks-of-neobanks”
  content/blog/the-benefits-and-risks-of-neobanks.md
  static/img/uploads/“what-is-a-neobank_”.jpg
Labels: netlify-cms/pending_review

#1074 Update Blog “the-basics-of-kyc-know-your-customer-kyc-fraud”
  content/blog/the-basics-of-kyc-know-your-customer-kyc-fraud.md
Labels: netlify-cms/pending_review

#1077 Create Blog “how-to-avoid-online-auction-fraud”
  content/blog/how-to-avoid-online-auction-fraud.md
  static/img/uploads/online-auction-fraud-wip-.jpg
Labels: netlify-cms/pending_review

#1075 Update Blog “account-takeover-indicators-that-businesses-should-know-to-prevent-digital-identity-fraud”
  content/blog/account-takeover-indicators-that-businesses-should-know-to-prevent-digital-identity-fraud.md
Labels: netlify-cms/pending_review

#1083 Update Notification Bar “notificationBar”
  content/notification-bar/notificationConfig.yml
Labels: netlify-cms/pending_publish

#1087 Create Blog “6-ways-to-prevent-ecommerce-return-fraud”
  content/blog/6-ways-to-prevent-ecommerce-return-fraud.md
  static/img/uploads/return-fraud.jpg
Labels: netlify-cms/pending_publish

#1100 Update Blog “6-types-of-ecommerce-fraud-and-how-to-prevent-them-from-compromising-your-online-store”
  content/blog/6-types-of-ecommerce-fraud-and-how-to-prevent-them-from-compromising-your-online-store.md
  static/img/uploads/seo-update_-6-types-of-ecommerce-fraud_-learn-how-to-tackle-them-and-secure-your-ecommerce-store.jpg
Labels: netlify-cms/pending_review

#1102 Create Blog “meet-the-fingerprint-team-at-merchant-risk-council-2023”
  content/blog/meet-the-fingerprint-team-at-merchant-risk-council-2023.md
  static/img/uploads/mrc-blogorange2.jpg
Labels: netlify-cms/pending_review

#1103 Create Author “tyler-von-harz”
  content/author/tyler-von-harz.md
  static/img/uploads/screen-shot-2022-08-30-at-5.08.13-pm.png
Labels: netlify-cms/pending_review

#1104 Update Blog “detect-sophisticated-bots-with-botd-by-fingerprint”
  content/blog/detect-sophisticated-bots-with-botd-by-fingerprint.md
Labels: netlify-cms/draft

#1106 Create Blog “what-you-need-to-know-about-bank-drop-scams”
  content/blog/what-you-need-to-know-about-bank-drop-scams.md
Labels: netlify-cms/pending_review

#1114 Create Blog “online-marketplace-fraud-how-to-protect-your-business-and-users”
  content/blog/online-marketplace-fraud-how-to-protect-your-business-and-users.md
  static/img/uploads/marketplace-fraud.jpg
Labels: netlify-cms/pending_review
